export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const HIDE_MESSAGE = "HIDE_MESSAGE";

export const REGISTER_BEGIN = "REGISTER_BEGIN";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const LOGOUT_USER = "LOGOUT_USER";

export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const UPLOAD_IMAGE_BEGIN = "UPLOAD_IMAGE_BEGIN";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_ERROR = "UPLOAD_IMAGE_ERROR";

export const CREATE_SHOW_BEGIN = "CREATE_SHOW_BEGIN";
export const CREATE_SHOW_SUCCESS = "CREATE_SHOW_SUCCESS";
export const CREATE_SHOW_ERROR = "CREATE_SHOW_ERROR";

export const GET_SHOWS_BEGIN = "GET_SHOWS_BEGIN";
export const GET_SHOWS_SUCCESS = "GET_SHOWS_SUCCESS";

export const SET_EDIT_SHOW = "SET_EDIT_SHOW";

export const DELETE_SHOW_BEGIN = "DELETE_SHOW_BEGIN";

export const EDIT_SHOW_BEGIN = "EDIT_SHOW_BEGIN";
export const EDIT_SHOW_SUCCESS = "EDIT_SHOW_SUCCESS";
export const EDIT_SHOW_ERROR = "EDIT_SHOW_ERROR";

export const CLEAR_VALUES = "CLEAR_VALUES";

export const CLEAR_FILE_UPLOAD = "CLEAR_FILE_UPLOAD";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";

export const SHOW_OVERVIEW_BEGIN = "SHOW_OVERVIEW_BEGIN";
export const SHOW_OVERVIEW_SUCCESS = "SHOW_OVERVIEW_SUCCESS";

export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const CHANGE_PAGE = "CHANGE_PAGE";

export const GET_PUBLISHED_SHOWS_BEGIN = "GET_PUBLISHED_SHOWS_BEGIN";
export const GET_PUBLISHED_SHOWS_SUCCESS = "GET_PUBLISHED_SHOWS_SUCCESS";

export const GET_FEATURED_SHOWS_BEGIN = "GET_FEATURED_SHOWS_BEGIN";
export const GET_FEATURED_SHOWS_SUCCESS = "GET_FEATURED_SHOWS_SUCCESS";

export const GET_UPCOMING_SHOWS_BEGIN = "GET_UPCOMING_SHOWS_BEGIN";
export const GET_UPCOMING_SHOWS_SUCCESS = "GET_UPCOMING_SHOWS_SUCCESS";

export const UPDATE_FAVORITE = "UPDATE_FAVORITE";
export const GET_FAVORITES = "GET_FAVORITES";
